version: '3'
services:
  # PHP Service
  todo-app:
    #image: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    user: www-todo
    container_name: todo-app
    tty: true
    environment:
      SERVICE_NAME: todo-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      #- ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - todo-network

  # Nginx Service
  todo-webserver:
    image: nginx:alpine
    container_name: todo-webserver
    tty: true
    ports:
      - "80:8080"
      - "8001:8080"      # Map Nginx HTTP on 8001 if needed
      - "4444:443"     # Map Nginx HTTPS to 4444
    volumes:
      - ./:/var/www
      - ./nginx/conf/test.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      - todo-network

  # PostgreSQL Service
  todo-db:
    build:
      context: ./debezium-postgres
      dockerfile: Dockerfile
    container_name: todo-db
    tty: true
    ports:
      - "5432:5432"   # Exposing on a non-standard port
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: postgresql
    volumes:
      - tododata:/var/lib/postgresql/data
    networks:
      - todo-network

  # Redis Service
  todo-redis:
    image: redis:alpine
    container_name: todo-redis
    ports:
      - "6380:6379"   # Exposing on a non-standard port
    volumes:
      - todo-redis-data:/data
    networks:
      - todo-network

# Docker Networks
networks:
  todo-network:
    driver: bridge
# Volumes
volumes:
  tododata:
    driver: local
  todo-redis-data:
    driver: local
