- name: Create a new VM from template on ESXi host
  hosts: esxi_host
  gather_facts: yes
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Update if necessary

  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "{{ ansible_host }}"
        username: root
        password: "{{ ansible_ssh_pass }}"
        validate_certs: no
        name: "new-ansible-vm"
        template: "jump-server"
        state: powered-on
        hardware:
          num_cpus: 2
          memory_mb: 4096
          num_cpu_cores_per_socket: 1
        networks:
          - name: "VM Network"
            type: static
            ip: "192.168.130.12"
            netmask: "255.255.255.0"
            gateway: "192.168.130.1"
        disk:
          - size_gb: 50
            type: thin
            datastore: "datastore1"
