- name: Clone running VM on ESXi
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone running VM (jump-server)
      community.vmware.vmware_vm_vm_docker:
        hostname: "192.168.130.210"
        username: "root"
        password: "Mid@s123"
        cluster: "ha-datacenter"  # specify the ESXi cluster if applicable
        datastore: "datastore1"  # specify the correct datastore
        folder: "/vmfs/volumes/datastore1/vm"  # specify the folder to create the VM in
        name: "new-ansible-vm"
        state: "powered-on"
        clone:
          template: "jump-server"  # Clone the running VM (jump-server)
          customize: true
          customize_spec:
            hostname: "new-ansible-vm"  # Set the hostname for the new VM
            memory_mb: 8192  # Memory for the new VM
            num_cpus: 2  # CPUs for the new VM
            network:
              - name: "VM Network"  # Specify the network for the VM
        validate_certs: false
