- name: Clone running VM on ESXi
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone running VM (jump-server)
      community.vmware.vmware_guest_instant_clone:
        hostname: "192.168.130.210"
        username: "root"
        password: "Mid@s123"
        cluster: "ha-datacenter"  # Specify the ESXi cluster if applicable
        datastore: "datastore1"  # Specify the correct datastore
        folder: "/vmfs/volumes/datastore1/vm"  # Specify the folder to create the VM in
        name: "new-ansible-vm"  # The name of the new VM
        state: "powered-on"
        clone:
          # Specify the name of the running VM that you want to clone
          source_vm: "jump-server"
          # Specify whether to power off the VM during the clone operation
          power_on: true
          # Optional customization options
          customize: true
          customize_spec:
            hostname: "new-ansible-vm"  # Set the hostname for the new VM
            memory_mb: 8192  # Memory for the new VM
            num_cpus: 2  # CPUs for the new VM
            network:
              - name: "VM Network"  # Specify the network for the VM
        validate_certs: false
