- name: Create a new VM from template on ESXi host
  hosts: localhost  # Run the tasks on the Ansible control machine (localhost)
  gather_facts: yes
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Make sure this points to the correct Python interpreter on your control machine
    vm_template: "jump-server"  # Template name
    new_vm_name: "new-ansible-vm"  # New VM name
    vm_network: "VM Network"  # Network to attach the VM to
    vm_ip: "192.168.130.12"  # IP address to assign to the VM
    vm_netmask: "255.255.255.0"  # Subnet mask
    vm_gateway: "192.168.130.1"  # Gateway
    vm_cpus: 2  # Number of CPUs
    vm_memory: 4096  # Amount of memory in MB
    datastore: "datastore1"  # Datastore where the VM should be stored
    ansible_ssh_pass: "Mid@s123"

  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "{{ ansible_host }}"
        username: root
        password: "{{ ansible_ssh_pass }}"
        validate_certs: no
        name: "{{ new_vm_name }}"
        template: "{{ vm_template }}"
        state: powered-on
        hardware:
          num_cpus: "{{ vm_cpus }}"
          memory_mb: "{{ vm_memory }}"
          num_cpu_cores_per_socket: 1
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "{{ vm_ip }}"
            netmask: "{{ vm_netmask }}"
            gateway: "{{ vm_gateway }}"
        disk:
          - size_gb: 50
            type: thin
            datastore: "{{ datastore }}"
      register: vm_creation_result

    - name: Check VM creation result
      debug:
        var: vm_creation_result
