- name: Install Docker and Docker Compose on remote Ubuntu VM
  hosts: localhost  # This is where the playbook starts, but we use `delegate_to` to target remote
  become: yes
  gather_facts: yes
  vars:
    remote_host: 192.168.130.108  # IP of the remote Ubuntu VM
    remote_user: ubuntu           # Username of the remote Ubuntu VM
    remote_password: ubuntu       # SSH password for the remote Ubuntu VM
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o PreferredAuthentications=password'

  tasks:
    - name: Set up connection to remote host
      set_fact:
        ansible_host: "{{ remote_host }}"
        ansible_user: "{{ remote_user }}"
        ansible_ssh_pass: "{{ remote_password }}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      delegate_to: localhost  # Ensure connection setup runs locally

    - name: Install aptitude on remote host
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
      delegate_to: "{{ ansible_host }}"  # Delegate to the remote host

    - name: Install required system packages on remote host
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      delegate_to: "{{ ansible_host }}"  # Delegate to the remote host

    - name: Add Docker GPG apt Key on remote host
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      delegate_to: "{{ ansible_host }}"  # Delegate to the remote host

    - name: Add Docker Repository on remote host
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      delegate_to: "{{ ansible_host }}"  # Delegate to the remote host

    - name: Update apt and install docker-ce on remote host
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
      delegate_to: "{{ ansible_host }}"  # Delegate to the remote host
