---
- name: Test SSH connection using password
  hosts: localhost  # Running locally
  gather_facts: no
  vars:
    remote_host: 192.168.130.108  # IP of the remote Ubuntu VM
    remote_user: ubuntu           # Username for SSH
    remote_password: ubuntu       # Password for SSH

  tasks:
    - name: Set up connection to remote host
      set_fact:
        ansible_host: "{{ remote_host }}"
        ansible_user: "{{ remote_user }}"
        ansible_ssh_pass: "{{ remote_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      delegate_to: localhost

    - name: Verify SSH connection by running a command on the remote host
      command: hostname
      delegate_to: "{{ ansible_host }}"
      register: result

    - name: Show remote hostname result
      debug:
        msg: "{{ result.stdout }}"
