---
- name: Install Docker and Docker Compose on remote Ubuntu VM
  hosts: localhost  # Run the playbook locally, but target the remote host
  become: yes
  gather_facts: yes
  vars:
    remote_host: 192.168.130.108  # IP of the remote Ubuntu VM
    remote_user: ubuntu           # Username of the remote Ubuntu VM
    remote_password: ubuntu       # SSH password for the remote Ubuntu VM
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o PreferredAuthentications=password'

  tasks:
    - name: Set up connection to remote host
      set_fact:
        ansible_host: "{{ remote_host }}"
        ansible_user: "{{ remote_user }}"
        ansible_ssh_pass: "{{ remote_password }}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      delegate_to: localhost

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up Docker stable repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started