---
- name: SSH Connection via sshpass to remote Ubuntu VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set up SSH connection using sshpass
      ansible.builtin.command:
        cmd: "sshpass -p '{{ ssh_password }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ssh_user }}@{{ remote_host }} 'hostname'"
      environment:
        SSH_ASKPASS: /usr/bin/ssh-askpass
      register: ssh_output
      delegate_to: localhost

    - name: Print SSH connection result
      debug:
        var: ssh_output.stdout

  vars:
    ssh_user: "ubuntu"  # Remote user on the Ubuntu VM
    ssh_password: "your_password_here"  # Password for the remote user
    remote_host: "192.168.130.108"  # IP of the remote Ubuntu VM
