---
- hosts: localhost
  name: Deploy Ubuntu VM from Template on ESXi
  gather_facts: false
  vars:
    esxi_host: "192.168.130.210"                            # ESXi host IP
    esxi_user: "root"                                        # ESXi username
    esxi_password: "Mid@s123"                                # ESXi password
    datastore: "datastore1"                                  # ESXi datastore
    template_path: "/vmfs/volumes/datastore1/iso/os_template/ubuntu-24.04/ubuntu.vmx"  # Full path to the template on ESXi
    vm_name: "ubuntu-server"                                 # VM name
    vm_disk_size: 50                                         # Disk size in GB
    vm_memory_size: 2048                                     # Memory size in MB
    vm_cpus: 1                                               # Number of CPUs
    vm_cpu_cores: 1                                          # CPU cores per socket
    vm_network: "VM Network"                                  # Network port group
    vmfolder: ""

  tasks:
    - name: Deploy Ubuntu VM from Template on ESXi
      community.vmware.vmware_guest:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_path }}"                      # Path to the template's VMX file on ESXi
        folder: "{{ vmfolder }}"
        datastore: "{{ datastore }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ vm_memory_size }}"
          num_cpus: "{{ vm_cpus }}"
          num_cpu_cores_per_socket: "{{ vm_cpu_cores }}"
          scsi: paravirtual
        networks:
          - name: "{{ vm_network }}"
            device_type: vmxnet3
        annotation: |
          *** Auto-Deployed by Ansible ***
          VM name: {{ vm_name }}
