---
- name: Create and Boot VM on ESXi Host using existing VMX and VMDK files
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Connect to ESXi host
      vmware_vm_vm_docker:
        hostname: "your-esxi-host"
        username: "your-username"
        password: "your-password"
        validate_certs: no
        state: "present"
        vm_id: "existing-vm-id"   # VM ID to register or boot (if exists)
        template: "no"
        esxi_host: "your-esxi-host"
        datastore: "datastore1"
        vmx_path: "/vmfs/volumes/datastore1/your-vm.vmx"
        vm_name: "YourVMName"
        wait_for_ip_address: yes
        power_on: yes
        folder: "/vmfs/volumes/datastore1/vm_folder"
        resource_pool: "Resources"

    - name: Power on VM if registered
      vmware_vm_vm_docker:
        hostname: "your-esxi-host"
        username: "your-username"
        password: "your-password"
        validate_certs: no
        state: "poweredon"
        name: "YourVMName"
