---
- name: Register and start a VM on standalone ESXi
  hosts: localhost
  gather_facts: no
  vars:
    esxi_host: "192.168.130.210"
    esxi_user: "root"
    esxi_password: "Mid@s123"
    vmx_path: "[datastore1] path/to/your-vm-folder/your-vm.vmx"  # Replace with the path to your .vmx file
    vm_name: "ansible-vm"  # Name to assign to the VM

  tasks:
    - name: Register VM from VMX file
      ansible.vmware.vmware_guest:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        folder: ""
        state: powered_on
        vmx_path: "{{ vmx_path }}"
      delegate_to: localhost
