name: Deploy Application via Docker Compose

on:
  push:
    branches:
      - dev  # Trigger on push to 'dev' branch or change this to your branch

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Clear Composer cache
        run: composer clear-cache
        
      - name: Install dependencies
        run: composer install --no-scripts --no-interaction --prefer-dist

      - name: Lint code with PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=PSR12 app/